### ISSUE TITLE
Provide preference setting for roadmap key colors

### ISSUE THREAD

**Issue by keller91711** [Impro-Visor/Impro-Visor#55]
Currently, roadmap key colors are wired into the code. At least one user would like to customize his colors. This request is to provide roadmap color customization in the preferences file.

**Comment by keller91711** [comment]
Now roadmap colors can be set in the My.preferences file. Colors are a list of S-expressions containing RGB values, in order of keys C, C#, D, etc.

**Comment by matimaui2** [comment]
i changed the rgb values in the my.preferences file but the colors in the roadmap haven´t changed, any ideas what might be the reason? thanks
